# Generated by Django 2.2.3 on 2019-08-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='ppid',
            field=models.IntegerField(default=0),
        ),
    ]
