# Generated by Django 2.2.3 on 2019-08-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190803_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='ppid',
        ),
    ]
