# Generated by Django 2.2.3 on 2019-08-13 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_detail_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='company',
            new_name='language',
        ),
        migrations.AddField(
            model_name='goods',
            name='publish_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
